# Generated by Django 4.2.2 on 2024-10-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='object_id',
        ),
    ]
