# Generated by Django 5.1.1 on 2024-10-15 16:51

import apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileattachment",
            name="id",
            field=apps.common.fields.Base58UUIDv5Field(primary_key=True, serialize=False),
        ),
    ]
