# Generated by Django 4.2.2 on 2024-10-02 21:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0014_delete_status'),
        ('product_management', '0051_remove_challenge_tag_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bounty',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='reward_type',
        ),
        migrations.AddField(
            model_name='bounty',
            name='reward_amount',
            field=models.PositiveIntegerField(default=0, help_text='Amount in points if reward_type is POINTS, or cents if reward_type is USD'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='reward_type',
            field=models.CharField(choices=[('Points', 'Points'), ('USD', 'Usd')], default='Points', max_length=10),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_management.challenge'),
        ),
        migrations.CreateModel(
            name='CompetitionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('content', models.TextField()),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Finalist', 'Finalist'), ('Winner', 'Winner'), ('Rejected', 'Rejected')], default='Submitted', max_length=20)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_entries', to='product_management.bounty')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_entries', to='talent.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Entries Closed', 'Entries Closed'), ('Judging', 'Judging'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('entry_deadline', models.DateTimeField()),
                ('judging_deadline', models.DateTimeField()),
                ('max_entries', models.PositiveIntegerField(blank=True, null=True)),
                ('attachments', models.ManyToManyField(blank=True, to='product_management.fileattachment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.product')),
                ('product_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_management.productarea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bounty',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_management.competition'),
        ),
        migrations.CreateModel(
            name='CompetitionEntryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5')),
                ('comment', models.TextField(blank=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='product_management.competitionentry')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to='talent.person')),
            ],
            options={
                'unique_together': {('entry', 'rater')},
            },
        ),
    ]
