# Generated by Django 4.2.2 on 2024-10-03 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpointaccount',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_point_account', to='product_management.product'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_transactions', to='commerce.organisationpointaccount'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='product_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_transactions', to='commerce.productpointaccount'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='commerce.salesorder'),
        ),
        migrations.AddField(
            model_name='organisationpointaccount',
            name='organisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_account', to='commerce.organisation'),
        ),
        migrations.AddField(
            model_name='bountycartitem',
            name='bounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.bounty'),
        ),
        migrations.AddField(
            model_name='bountycartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.bountycart'),
        ),
        migrations.AddField(
            model_name='bountycart',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.organisation'),
        ),
        migrations.AddField(
            model_name='bountycart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.product'),
        ),
    ]
