# Generated by Django 5.1.1 on 2024-10-09 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bountycart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.product'),
        ),
    ]
