# Generated by Django 5.1.1 on 2024-10-08 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0002_initial'),
        ('product_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bountycart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bountycartitem',
            name='bounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.bounty'),
        ),
        migrations.AddField(
            model_name='bountycartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.bountycart'),
        ),
        migrations.AddField(
            model_name='bountycart',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.organisation'),
        ),
        migrations.AddField(
            model_name='organisationpointaccount',
            name='organisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_account', to='commerce.organisation'),
        ),
        migrations.AddField(
            model_name='organisationpointgrant',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisationpointgrant',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_grants', to='commerce.organisation'),
        ),
        migrations.AddField(
            model_name='platformfee',
            name='bounty_cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_fee', to='commerce.bountycart'),
        ),
        migrations.AddField(
            model_name='pointorder',
            name='bounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_orders', to='product_management.bounty'),
        ),
        migrations.AddField(
            model_name='pointorder',
            name='bounty_cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_order', to='commerce.bountycart'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_transactions', to='commerce.organisationpointaccount'),
        ),
        migrations.AddField(
            model_name='productpointaccount',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_point_account', to='product_management.product'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='product_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_transactions', to='commerce.productpointaccount'),
        ),
        migrations.AddField(
            model_name='pointorder',
            name='product_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_orders', to='commerce.productpointaccount'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='bounty_cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order', to='commerce.bountycart'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='platform_fee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order', to='commerce.platformfee'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='commerce.salesorder'),
        ),
    ]
